# Development environment overrides

app:
  environment: "development"

global:
  imageRegistry: ""

serviceAccount:
  create: false

# Disable bundled ingress; local cluster uses standalone manifest
ingress:
  enabled: false
  host: 254carbon.local

ingress-nginx:
  enabled: false

cert-manager:
  enabled: false

external-secrets:
  enabled: false

# Reduced resource requirements for dev
services:
  api-gateway:
    image:
      registry: ""
    replicas: 1
    env:
      - name: ENABLE_GRAPHQL
        value: "true"
      - name: ENABLE_ANALYTICS
        value: "true"
      - name: ENABLE_RESEARCH
        value: "true"
      - name: ENABLE_ALERTS
        value: "false"
      - name: CLICKHOUSE_HOST
        value: "clickhouse"
      - name: CLICKHOUSE_PORT
        value: "9000"
    readinessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 6
    livenessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 3
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

  curve-service:
    image:
      registry: ""
    replicas: 1
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi

  scenario-engine:
    image:
      registry: ""
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

  backtesting-service:
    image:
      registry: ""
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

  download-center:
    image:
      registry: ""
    replicas: 1
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 125m
        memory: 128Mi

  web-hub:
    image:
      registry: ""
    replicas: 1
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 125m
        memory: 128Mi

# Disable blue-green for dev
blueGreen:
  enabled: false

# Disable HPA for dev
hpa:
  enabled: false

# Disable PDB for dev
pdb:
  enabled: false

# Relaxed monitoring for dev
monitoring:
  enabled: false

