# Backtesting Service Deployment and Service
# - Exposes HTTP on 8005
# - Depends on PostgreSQL and ClickHouse
# - ImagePullPolicy set to Never for local dev; adjust for CI/CD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backtesting-service
  namespace: market-intelligence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backtesting-service
  template:
    metadata:
      labels:
        app: backtesting-service
    spec:
      containers:
      - name: backtesting-service
        image: docker.io/254carbon/backtesting-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8005
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:postgres@postgresql:5432/market_intelligence
        - name: CLICKHOUSE_HOST
          value: clickhouse
        - name: PYTHONPATH
          value: /app
        - name: ENVIRONMENT
          value: development
---
apiVersion: v1
kind: Service
metadata:
  name: backtesting-service
  namespace: market-intelligence
spec:
  selector:
    app: backtesting-service
  ports:
  - port: 8005
    targetPort: 8005
  type: ClusterIP
# Kubernetes Deployment for Backtesting Service
# - Exposes REST endpoints for running and evaluating backtests
# - Tune resources/replicas based on workload
