# Nightly ClickHouse backup to MinIO (daily at 02:00 UTC)
# - Uses clickhouse-client BACKUP to S3-compatible endpoint
# - Credentials from Kubernetes Secrets
apiVersion: batch/v1
kind: CronJob
metadata:
  name: clickhouse-backup-daily
  namespace: market-intelligence
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup
            image: clickhouse/clickhouse-server:25.9.2.1
            env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: access_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: secret_key
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: clickhouse-credentials
                  key: username
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse-credentials
                  key: password
            command: ["/bin/sh","-lc"]
            args:
            - |
              set -eu
              ts=$(date -u +%Y%m%dT%H%M%SZ)
              clickhouse-client -h clickhouse -u "$CLICKHOUSE_USER" --password "$CLICKHOUSE_PASSWORD" \
                -q "BACKUP DATABASE market_intelligence TO S3('http://minio:9000/clickhouse-backups/daily/${ts}', '$MINIO_ACCESS_KEY', '$MINIO_SECRET_KEY')"
