# PodDisruptionBudget for ClickHouse single replica
# Ensures no voluntary disruptions when only one pod exists
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: clickhouse-pdb
  namespace: market-intelligence
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: clickhouse
