# One-off job to create the MinIO bucket for ClickHouse backups
# Idempotent: will succeed if the bucket already exists
apiVersion: batch/v1
kind: Job
metadata:
  name: ensure-clickhouse-backup-bucket
  namespace: market-intelligence
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mc
        image: minio/mc:latest
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: access_key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secret_key
        command: ["/bin/sh","-lc"]
        args:
        - |
          mc alias set local http://minio:9000 "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY" && \
          mc mb -p local/clickhouse-backups || \
          echo "bucket exists"
