# ClickHouse data volume (PVC)
# - StorageClass: standard (rancher.io/local-path), no online expansion
# - Capacity: 1Ti (recreated via backup/restore during migration)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-pvc
  namespace: market-intelligence
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: standard
