# API Gateway Deployment and Service
# - Exposes HTTP on 8000
# - Talks to PostgreSQL, ClickHouse, Kafka
# - Set appropriate image tag and pull policy for your environment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: market-intelligence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: docker.io/254carbon/gateway:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:postgres@postgresql:5432/market_intelligence
        - name: CLICKHOUSE_HOST
          value: clickhouse
        - name: KAFKA_BOOTSTRAP
          value: kafka:9092
        - name: PYTHONPATH
          value: /app
        - name: ENVIRONMENT
          value: development
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: market-intelligence
spec:
  selector:
    app: gateway
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
# Kubernetes Deployment for API Gateway
# - Fronts platform services and handles HTTP/WebSocket traffic
