# NGINX Ingress for Gateway and Web Hub
# - Host: 254carbon.local (adjust DNS/hosts accordingly)
# - /api -> gateway:8000, /web and / -> web-hub:3000
# - SSL redirect disabled for local dev
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 254carbon-ingress
  namespace: market-intelligence
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: 254carbon.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: gateway
            port:
              number: 8000
      - path: /web
        pathType: Prefix
        backend:
          service:
            name: web-hub
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-hub
            port:
              number: 3000
