# Keycloak Deployment and Service (dev profile)
# - Exposes HTTP on 8080
# - For production, enable persistent storage and TLS
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: market-intelligence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:23.0
        ports:
        - containerPort: 8080
        env:
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: admin
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL
          value: jdbc:postgresql://postgresql:5432/keycloak
        - name: KC_DB_USERNAME
          value: postgres
        - name: KC_DB_PASSWORD
          value: postgres
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "false"
        command: ["/opt/keycloak/bin/kc.sh", "start-dev"]
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: market-intelligence
spec:
  selector:
    app: keycloak
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
# Keycloak identity provider deployment
# - Manages authentication/authorization for the platform
