# MetalLB address pool and L2 advertisement (kind dev)
# - Provides LoadBalancer IPs in 172.18.255.200-250
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.18.255.200-172.18.255.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - default-pool
# MetalLB configuration for LoadBalancer IP address pools
