# MinIO credentials for backup jobs (dev defaults)
# Replace with production credentials or manage via External Secrets
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: market-intelligence
type: Opaque
stringData:
  access_key: minioadmin
  secret_key: minioadmin
