# PostgreSQL Deployment and Service
# - Exposes 5432
# - Initialized by postgresql-init-configmap.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: market-intelligence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: market_intelligence
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        volumeMounts:
        - name: postgresql-storage
          mountPath: /var/lib/postgresql/data
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d/
      volumes:
      - name: postgresql-storage
        persistentVolumeClaim:
          claimName: postgresql-pvc
      - name: init-script
        configMap:
          name: postgresql-init
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: market-intelligence
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
