apiVersion: apps/v1
kind: Deployment
metadata:
  name: routing-service
  namespace: market-intelligence
  labels:
    app: routing-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: routing-service
  template:
    metadata:
      labels:
        app: routing-service
        tier: backend
    spec:
      containers:
      - name: routing-service
        image: 254carbon/routing-service:latest
        ports:
        - containerPort: 8007
          name: http
        env:
        - name: POSTGRES_HOST
          value: "postgresql"
        - name: POSTGRES_DB
          value: "market_intelligence"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8007
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8007
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: routing-service
  namespace: market-intelligence
  labels:
    app: routing-service
spec:
  type: ClusterIP
  ports:
  - port: 8007
    targetPort: 8007
    protocol: TCP
    name: http
  selector:
    app: routing-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: routing-service-pdb
  namespace: market-intelligence
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: routing-service
