apiVersion: apps/v1
kind: Deployment
metadata:
  name: scenario-engine
  namespace: market-intelligence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scenario-engine
  template:
    metadata:
      labels:
        app: scenario-engine
    spec:
      containers:
      - name: scenario-engine
        image: docker.io/254carbon/scenario-engine:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:postgres@postgresql:5432/market_intelligence
        - name: CLICKHOUSE_HOST
          value: clickhouse
        - name: S3_ENDPOINT
          value: http://minio:9000
        - name: PYTHONPATH
          value: /app
        - name: ENVIRONMENT
          value: development
---
apiVersion: v1
kind: Service
metadata:
  name: scenario-engine
  namespace: market-intelligence
spec:
  selector:
    app: scenario-engine
  ports:
  - port: 8002
    targetPort: 8002
  type: ClusterIP
