apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-insights
  namespace: market-intelligence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-insights
  template:
    metadata:
      labels:
        app: market-insights
    spec:
      containers:
      - name: market-insights
        image: 254carbon/market-insights:latest
        ports:
        - containerPort: 8015
        env:
        - name: CLICKHOUSE_HOST
          value: "clickhouse"
        - name: CLICKHOUSE_PORT
          value: "9000"
        - name: POSTGRES_HOST
          value: "postgresql"
        - name: POSTGRES_PORT
          value: "5432"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8015
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8015
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: market-insights
  namespace: market-intelligence
spec:
  selector:
    app: market-insights
  ports:
  - port: 8015
    targetPort: 8015
  type: ClusterIP
