apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlp-service
  namespace: market-intelligence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nlp-service
  template:
    metadata:
      labels:
        app: nlp-service
    spec:
      containers:
      - name: nlp-service
        image: 254carbon/nlp-service:latest
        ports:
        - containerPort: 8014
        env:
        - name: POSTGRES_HOST
          value: "postgresql"
        - name: POSTGRES_PORT
          value: "5432"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8014
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8014
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: nlp-service
  namespace: market-intelligence
spec:
  selector:
    app: nlp-service
  ports:
  - port: 8014
    targetPort: 8014
  type: ClusterIP
