server:
  ha:
    enabled: true
  dataStorage:
    enabled: true
    size: 32Gi
  auditStorage:
    enabled: true
    size: 10Gi
  ingress:
    enabled: true
    hosts:
      - vault.{{ .Values.baseDomain }}
  extraEnvironmentVars:
    VAULT_RAFT_NODE_ID: "vault-0"
  service:
    type: ClusterIP
injector:
  enabled: true
ui:
  enabled: true
serverTelemetry:
  serviceMonitor:
    enabled: true
