apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: 254carbon-rules
  namespace: monitoring
spec:
  groups:
  - name: 254carbon
    rules:
    - alert: HighAPILatency
      expr: histogram_quantile(0.95, rate(254carbon_api_request_duration_seconds_bucket[5m])) > 0.25
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High API latency detected"
        description: "API p95 latency is above 250ms for 5 minutes"

    - alert: LowDataCompleteness
      expr: 254carbon_data_completeness < 0.995
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "Low data completeness"
        description: "Data completeness is below 99.5% for 10 minutes"

    - alert: ForecastAccuracyDegraded
      expr: 254carbon_forecast_mape > 0.12
      for: 1h
      labels:
        severity: warning
      annotations:
        summary: "Forecast accuracy degraded"
        description: "MAPE is above 12% for 1 hour"

    - alert: ServiceDown
      expr: up{job=~"254carbon-.+"} == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "254Carbon service is down"
        description: "Service {{ $labels.job }} has been down for more than 2 minutes"
