apiVersion: batch/v1
kind: CronJob
metadata:
  name: secrets-rotation
  namespace: market-intelligence
spec:
  schedule: "0 2 1 * *"  # Monthly at 2 AM on the 1st
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: secrets-rotation
        spec:
          serviceAccountName: secrets-manager
          containers:
          - name: rotate-secrets
            image: bitnami/kubectl:latest
            command:
            - /bin/bash
            - -c
            - |
              set -e
              
              echo "Starting secrets rotation..."
              
              # Rotate database password
              NEW_DB_PASSWORD=$(openssl rand -base64 32)
              kubectl create secret generic db-credentials \
                --from-literal=password=$NEW_DB_PASSWORD \
                --dry-run=client -o yaml | kubectl apply -f -
              
              # Update PostgreSQL password
              kubectl exec -n market-intelligence-infra postgresql-0 -- \
                psql -U postgres -c "ALTER USER postgres PASSWORD '$NEW_DB_PASSWORD';"
              
              # Rotate MinIO credentials
              NEW_MINIO_ACCESS_KEY=$(openssl rand -hex 16)
              NEW_MINIO_SECRET_KEY=$(openssl rand -base64 32)
              kubectl create secret generic minio-credentials \
                --from-literal=access_key=$NEW_MINIO_ACCESS_KEY \
                --from-literal=secret_key=$NEW_MINIO_SECRET_KEY \
                --dry-run=client -o yaml | kubectl apply -f -
              
              # Rotate API keys
              NEW_API_KEY=$(openssl rand -hex 32)
              kubectl create secret generic api-keys \
                --from-literal=internal_key=$NEW_API_KEY \
                --dry-run=client -o yaml | kubectl apply -f -
              
              # Rollout restart services to pick up new secrets
              kubectl rollout restart deployment/api-gateway -n market-intelligence
              kubectl rollout restart deployment/curve-service -n market-intelligence
              kubectl rollout restart deployment/scenario-engine -n market-intelligence
              
              echo "Secrets rotation completed successfully"
              
              # Log to audit
              kubectl exec -n market-intelligence-infra postgresql-0 -- \
                psql -U postgres -d market_intelligence -c \
                "INSERT INTO pg.audit_log (user_id, action, resource_type, resource_id, success) \
                VALUES ('system', 'secrets_rotation', 'secrets', 'all', true);"
          restartPolicy: OnFailure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-manager
  namespace: market-intelligence
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-manager-role
  namespace: market-intelligence
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-manager-binding
  namespace: market-intelligence
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secrets-manager-role
subjects:
- kind: ServiceAccount
  name: secrets-manager
  namespace: market-intelligence

