apiVersion: apps/v1
kind: Deployment
metadata:
  name: download-center
  namespace: market-intelligence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: download-center
  template:
    metadata:
      labels:
        app: download-center
    spec:
      containers:
      - name: download-center
        image: 254carbon/download-center:latest
        ports:
        - containerPort: 8007
        env:
        - name: MINIO_HOST
          value: "minio"
        - name: MINIO_PORT
          value: "9000"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secret-key
        - name: POSTGRES_HOST
          value: "postgresql"
        - name: POSTGRES_PORT
          value: "5432"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8007
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8007
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: download-center
  namespace: market-intelligence
spec:
  selector:
    app: download-center
  ports:
  - port: 8007
    targetPort: 8007
  type: ClusterIP
