apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
  namespace: market-intelligence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
      - name: report-service
        image: 254carbon/report-service:latest
        ports:
        - containerPort: 8010
        env:
        - name: CLICKHOUSE_HOST
          value: "clickhouse"
        - name: CLICKHOUSE_PORT
          value: "9000"
        - name: POSTGRES_HOST
          value: "postgresql"
        - name: POSTGRES_PORT
          value: "5432"
        - name: MINIO_HOST
          value: "minio"
        - name: MINIO_PORT
          value: "9000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: report-service
  namespace: market-intelligence
spec:
  selector:
    app: report-service
  ports:
  - port: 8010
    targetPort: 8010
  type: ClusterIP
