apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydrogen-service
  namespace: market-intelligence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hydrogen-service
  template:
    metadata:
      labels:
        app: hydrogen-service
    spec:
      containers:
      - name: hydrogen-service
        image: 254carbon/hydrogen-service:latest
        ports:
        - containerPort: 8012
        env:
        - name: CLICKHOUSE_HOST
          value: "clickhouse"
        - name: CLICKHOUSE_PORT
          value: "9000"
        - name: POSTGRES_HOST
          value: "postgresql"
        - name: POSTGRES_PORT
          value: "5432"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8012
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8012
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: hydrogen-service
  namespace: market-intelligence
spec:
  selector:
    app: hydrogen-service
  ports:
  - port: 8012
    targetPort: 8012
  type: ClusterIP
