{{- if .Values.static.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: airflow-postgres
  namespace: data-platform
  labels:
    app.kubernetes.io/managed-by: platform-secrets
    app.kubernetes.io/name: airflow-postgres
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/component: secret
    app.kubernetes.io/version: "1"
type: Opaque
data:
  connection: {{ (env "AIRFLOW_PG_CONN" | default .Values.airflow.connection) | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: openmetadata-postgres
  namespace: data-platform
  labels:
    app.kubernetes.io/managed-by: platform-secrets
    app.kubernetes.io/name: openmetadata-postgres
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/component: secret
    app.kubernetes.io/version: "1"
type: Opaque
data:
  password: {{ (env "OPENMETADATA_DB_PASS" | default .Values.openmetadata.password) | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-postgres
  namespace: data-platform
  labels:
    app.kubernetes.io/managed-by: platform-secrets
    app.kubernetes.io/name: mlflow-postgres
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/component: secret
    app.kubernetes.io/version: "1"
type: Opaque
data:
  connection: {{ (env "MLFLOW_PG_CONN" | default .Values.mlflow.connection) | b64enc | quote }}
{{- end }}
