# GEM Transmission Connector (Config/CronJob/Monitoring)
# -----------------------------------------------------
# Ingests Global Energy Monitor transmission infrastructure data on a schedule
# and exposes Prometheus metrics for health/throughput. This manifest groups
# the ConfigMap, Secret, CronJob, Service, and ServiceMonitor for the connector.
apiVersion: v1
kind: ConfigMap
metadata:
  name: gem-transmission-connector-config
  namespace: market-intelligence
data:
  config.yaml: |
    source_id: gem_transmission
    api_base: https://api.globalenergymonitor.org/v1
    regions:
      - global
    min_voltage_kv: 100
    include_projects: true
    project_statuses:
      - construction
      - commissioned
      - pre_construction
    kafka:
      topic: market.infrastructure
      bootstrap_servers: kafka:9092
    database:
      host: postgresql
      port: 5432
      database: market_intelligence
      user: postgres
      checkpoint_min_interval_seconds: 300
---
apiVersion: v1
kind: Secret
metadata:
  name: gem-transmission-connector-secrets
  namespace: market-intelligence
type: Opaque
stringData:
  api_key: ${GEM_API_KEY}
  db_password: ${POSTGRES_PASSWORD}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: gem-transmission-connector
  namespace: market-intelligence
spec:
  schedule: "0 4 * * 3"  # Weekly on Wednesday at 4 AM
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: gem-transmission-connector
            component: infrastructure
        spec:
          restartPolicy: OnFailure
          containers:
          - name: connector
            image: 254carbon/infrastructure-connectors:latest
            command: ["python", "-m", "data.connectors.external.infrastructure.gem_transmission_connector"]
            env:
            - name: GEM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gem-transmission-connector-secrets
                  key: api_key
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gem-transmission-connector-secrets
                  key: db_password
            - name: CONFIG_PATH
              value: /config/config.yaml
            volumeMounts:
            - name: config
              mountPath: /config
            resources:
              requests:
                memory: "1Gi"
                cpu: "500m"
              limits:
                memory: "2Gi"
                cpu: "1"
          volumes:
          - name: config
            configMap:
              name: gem-transmission-connector-config
---
apiVersion: v1
kind: Service
metadata:
  name: gem-transmission-connector-metrics
  namespace: market-intelligence
  labels:
    app: gem-transmission-connector
spec:
  selector:
    app: gem-transmission-connector
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gem-transmission-connector
  namespace: market-intelligence
spec:
  selector:
    matchLabels:
      app: gem-transmission-connector
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
