---
# Pod Security Policy for 254Carbon Production Deployment
# Enforces security best practices for all pods

# Restricted Pod Security Policy (most secure)
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted-policy
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'

---
# Baseline Pod Security Policy (moderate security)
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: baseline-policy
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
    - 'nfs'
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'

---
# Cluster Role for Restricted Policy
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: restricted-psp-role
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames: ['restricted-policy']

---
# Cluster Role for Baseline Policy
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: baseline-psp-role
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames: ['baseline-policy']

---
# Cluster Role Binding for Application Services (Baseline Policy)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: market-intelligence-baseline-psp
roleRef:
  kind: ClusterRole
  name: baseline-psp-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: market-intelligence-sa
  namespace: market-intelligence

---
# Cluster Role Binding for Data Connectors (Baseline Policy)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: data-connector-baseline-psp
roleRef:
  kind: ClusterRole
  name: baseline-psp-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: data-connector-sa
  namespace: market-intelligence

---
# Cluster Role Binding for Monitoring (Restricted Policy)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-restricted-psp
roleRef:
  kind: ClusterRole
  name: restricted-psp-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: monitoring-sa
  namespace: market-intelligence-infra

---
# Pod Security Admission Configuration (for Kubernetes 1.25+)
apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-security-admission-config
  namespace: kube-system
data:
  pod-security.yaml: |
    apiVersion: pod-security.admission.config.k8s.io/v1beta1
    kind: PodSecurityConfiguration
    defaults:
      enforce: "baseline"
      enforce-version: "latest"
      audit: "restricted"
      audit-version: "latest"
      warn: "restricted"
      warn-version: "latest"
    exemptions:
      usernames: []
      runtimeClasses: []
      namespaces: []

---
# Namespace Labels for Pod Security Standards
apiVersion: v1
kind: Namespace
metadata:
  name: market-intelligence
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

---
apiVersion: v1
kind: Namespace
metadata:
  name: market-intelligence-infra
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

---
# Security Context Constraints (OpenShift compatible)
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: market-intelligence-scc
allowPrivilegedContainer: false
allowPrivilegeEscalation: false
requiredDropCapabilities:
  - ALL
runAsUser:
  type: MustRunAsNonRoot
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
users:
  - system:serviceaccount:market-intelligence:market-intelligence-sa
  - system:serviceaccount:market-intelligence:data-connector-sa

---
# Resource Quota for Namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: market-intelligence-quota
  namespace: market-intelligence
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "20"
    pods: "50"
    services: "20"
    secrets: "50"
    configmaps: "50"

---
# Limit Range for Container Resources
apiVersion: v1
kind: LimitRange
metadata:
  name: market-intelligence-limits
  namespace: market-intelligence
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    max:
      cpu: "2"
      memory: 4Gi
    min:
      cpu: 50m
      memory: 100Mi
    type: Container
# Pod security configurations (Baseline/Restricted)
# - Prefer PodSecurity admission over legacy PSPs in new clusters
