# Infrastructure Helm Values
# Local Kubernetes deployment

# Kafka
kafka:
  enabled: true
  replicaCount: 1
  zookeeper:
    enabled: true
    replicaCount: 1
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "2"

# ClickHouse
clickhouse:
  enabled: true
  replicaCount: 1
  persistence:
    enabled: true
    size: 50Gi
  resources:
    requests:
      memory: "4Gi"
      cpu: "2"
    limits:
      memory: "8Gi"
      cpu: "4"
  config:
    maxMemoryUsage: 10000000000
    maxThreads: 8

# PostgreSQL
postgresql:
  enabled: true
  auth:
    postgresPassword: "postgres"
    database: "market_intelligence"
  primary:
    persistence:
      enabled: true
      size: 20Gi
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1"

# MinIO (S3-compatible object storage)
minio:
  enabled: true
  mode: standalone
  rootUser: minioadmin
  rootPassword: minioadmin
  persistence:
    enabled: true
    size: 100Gi
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
  buckets:
    - name: raw
      policy: none
    - name: curves
      policy: none
    - name: runs
      policy: none
    - name: downloads
      policy: download

# Keycloak (OIDC)
keycloak:
  enabled: true
  auth:
    adminUser: admin
    adminPassword: admin
  postgresql:
    enabled: true
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
  ingress:
    enabled: true
    hostname: keycloak.local

# Prometheus
prometheus:
  enabled: true
  server:
    retention: "15d"
    persistentVolume:
      enabled: true
      size: 20Gi
    resources:
      requests:
        memory: "2Gi"
        cpu: "1"
  alertmanager:
    enabled: true

# Grafana
grafana:
  enabled: true
  adminPassword: admin
  persistence:
    enabled: true
    size: 5Gi
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server
          isDefault: true
        - name: ClickHouse
          type: vertamedia-clickhouse-datasource
          url: http://clickhouse:8123
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          folder: 'Market Intelligence'
          type: file
          options:
            path: /var/lib/grafana/dashboards

# Apache Airflow
airflow:
  enabled: true
  executor: KubernetesExecutor
  postgresql:
    enabled: true
  redis:
    enabled: false
  env:
    - name: KAFKA_BOOTSTRAP
      value: kafka:9092
    - name: NOAA_CDO_API_BASE
      value: https://www.ncdc.noaa.gov/cdo-web/api/v2
    - name: WB_API_BASE
      value: https://api.worldbank.org/v2
    - name: NOAA_CDO_TOKEN
      valueFrom:
        secretKeyRef:
          name: noaa-cdo-token
          key: token
    - name: AESO_BEARER_TOKEN
      valueFrom:
        secretKeyRef:
          name: aeso-api-credentials
          key: bearer-token
    # ERA5 defaults (can be overridden by Airflow Variables)
    - name: ERA5_DATASET
      value: reanalysis-era5-single-levels
    - name: ERA5_VARIABLES
      value: "2m_temperature,10m_u_component_of_wind,10m_v_component_of_wind,total_precipitation"
    - name: ERA5_AREA
      value: ""  # format: N,W,S,E (e.g., 50,-130,25,-65)
    - name: ERA5_HOURS
      value: ""  # csv HH:MM list; default is all 24 hours when empty
    - name: ERA5_LATITUDE
      value: ""
    - name: ERA5_LONGITUDE
      value: ""
    - name: ERA5_SCHEDULE
      value: "0 3 * * *"
    - name: ERA5_BACKFILL_START
      value: ""
    - name: ERA5_BACKFILL_END
      value: ""
    - name: ERA5_BACKFILL_CHUNK_DAYS
      value: "1"
    - name: CDS_URL
      value: https://cds.climate.copernicus.eu/api/v2
    - name: CDS_KEY
      value: ""  # prefer ~/.cdsapirc or set via Airflow Variable
    # Copernicus CDS defaults (can be overridden by Airflow Variables)
    - name: CDS_DATASET
      value: reanalysis-era5-single-levels
    - name: CDS_VARIABLES
      value: "2m_temperature,10m_u_component_of_wind,10m_v_component_of_wind,total_precipitation"
    - name: CDS_AREA
      value: ""  # format: N,W,S,E (e.g., 50,-130,25,-65)
    - name: CDS_HOURS
      value: ""  # csv HH:MM list; default all 24h when empty
    - name: CDS_LATITUDE
      value: ""
    - name: CDS_LONGITUDE
      value: ""
    - name: CDS_SCHEDULE
      value: "0 4 * * *"
    - name: CDS_BACKFILL_START
      value: ""
    - name: CDS_BACKFILL_END
      value: ""
    - name: CDS_BACKFILL_CHUNK_DAYS
      value: "1"
    - name: WB_COUNTRY
      value: WLD
    - name: WB_ENERGY_INDICATORS
      value: EG.USE.PCAP.KG.OE,EG.ELC.ACCS.ZS
    - name: WB_ECON_INDICATORS
      value: NY.GDP.PCAP.CD,FP.CPI.TOTL.ZG
    - name: WB_START_YEAR
      value: "2010"
    - name: WB_END_YEAR
      value: "2025"
    - name: NOAA_CDO_LIMIT
      value: "1000"
    # EIA defaults
    - name: EIA_API_BASE
      value: https://api.eia.gov/v2
    - name: EIA_API_KEY
      valueFrom:
        secretKeyRef:
          name: eia-api-credentials
          key: api-key
    - name: EIA_SCHEDULE
      value: "@weekly"
    - name: EIA_DATASETS
      value: ""  # csv list of dataset paths
    - name: EIA_QUERIES
      value: ""  # JSON array of advanced query specs
    - name: EIA_BACKFILL_START
      value: ""
    - name: EIA_BACKFILL_END
      value: ""
    - name: EIA_BACKFILL_STEP_MONTHS
      value: "6"
    - name: EIA_STORAGE_QUERIES
      value: ""  # JSON array of storage query specs
    # AGSI+ defaults
    - name: AGSI_API_BASE
      value: https://agsi.gie.eu/api/v1
    - name: AGSI_API_KEY
      valueFrom:
        secretKeyRef:
          name: agsi-api-credentials
          key: api-key
    - name: AGSI_GRANULARITY
      value: facility
    - name: AGSI_ENTITIES
      value: ""  # optional CSV of facility/country codes
    - name: AGSI_INCLUDE_ROLLUPS
      value: "true"
    - name: AGSI_SCHEDULE
      value: "0 6 * * *"
    # ENTSO-E defaults
    - name: ENTSOE_API_BASE
      value: https://web-api.tp.entsoe.eu
    - name: ENTSOE_SECURITY_TOKEN
      valueFrom:
        secretKeyRef:
          name: entsoe-api-credentials
          key: security-token
    - name: ENTSOE_SCHEDULE
      value: "0 5 * * *"
    - name: ENTSOE_AREA
      value: 10Y1001A1001A83F
    - name: ENTSOE_OUT_AREA
      value: ""
    - name: ENTSOE_MODES
      value: load,generation
    - name: ENTSOE_PERIOD_START
      value: ""
    - name: ENTSOE_PERIOD_END
      value: ""
    - name: ENTSOE_BACKFILL_START
      value: ""
    - name: ENTSOE_BACKFILL_END
      value: ""
    - name: ENTSOE_BACKFILL_STEP_HOURS
      value: "24"
    - name: ENTSOE_AREA_NAMES
      value: ""  # JSON mapping of EIC → friendly names
    # Open Infrastructure Map defaults
    - name: OIM_SCHEDULE
      value: "@weekly"
    - name: OIM_OVERPASS_URL
      value: https://overpass-api.de/api/interpreter
    - name: OIM_BBOX
      value: ""  # south,west,north,east
    - name: OIM_AREA_ID
      value: ""  # OSM area id
    - name: OIM_REGION_NAME
      value: WORLD
    - name: COAL_SITES_CSV
      value: /opt/airflow/dags/platform/data/reference/coal_sites.csv
    - name: SATELLITE_INTEL_BASE
      value: http://satellite-intel:8025
    - name: COAL_STOCKPILE_SCHEDULE
      value: "0 5 * * MON"
    - name: LNG_LOOKBACK_HOURS
      value: "24"
    - name: LNG_PROVIDER
      value: adapter_stub
    - name: LNG_TERMINAL_FILE
      value: /opt/airflow/dags/platform/data/reference/lng_terminals.geojson
    # US Census defaults
    - name: CENSUS_API_BASE
      value: https://api.census.gov/data
    - name: CENSUS_API_KEY
      valueFrom:
        secretKeyRef:
          name: census-api-credentials
          key: api-key
    - name: CENSUS_SCHEDULE
      value: "@monthly"
    - name: CENSUS_QUERIES
      value: ""  # JSON array of query specs
    - name: CENSUS_BACKFILL_START_YEAR
      value: "2010"
    - name: CENSUS_BACKFILL_END_YEAR
      value: "2025"
  webserver:
    defaultUser:
      enabled: true
      username: admin
      password: admin
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
