apiVersion: apps/v1
kind: Deployment
metadata:
  name: lmp-decomposition-service
  namespace: market-intelligence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lmp-decomposition-service
  template:
    metadata:
      labels:
        app: lmp-decomposition-service
    spec:
      containers:
      - name: lmp-decomposition-service
        image: 254carbon/lmp-decomposition-service:latest
        ports:
        - containerPort: 8009
        env:
        - name: CLICKHOUSE_HOST
          value: "clickhouse"
        - name: CLICKHOUSE_PORT
          value: "9000"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8009
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8009
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: lmp-decomposition-service
  namespace: market-intelligence
spec:
  selector:
    app: lmp-decomposition-service
  ports:
  - port: 8009
    targetPort: 8009
  type: ClusterIP
